### ISSUE TITLE
Hide status bar and navigation bar

### ISSUE THREAD

**Issue by giagiar** [Optoma/optoma-projector-launcher#4]
for all the pages

<img width="1213" alt="screen shot 2017-05-24 at 18 16 54" src="https://cloud.githubusercontent.com/assets/23302243/26399107/430df870-40ae-11e7-9f49-c3c21b891037.png">

**Comment by kuanyingchou** [comment]
We need a way to disable these bars in the system, not in the launcher app. Otherwise, when user opens any other app, say Facebook, these bars would appear again. 

I think we should ask Coretronic whether they have implemented this feature. If not, we can try to implement it once we have a custom rom, preferably from Coretronic.

**Comment by kuanyingchou** [comment]
One way to disable them temporarily is through adb:

```
adb shell settings put global policy_control immersive.full=*
```

From: http://forums.crackberry.com/blackberry-priv-f440/guide-hide-navigation-status-bar-adb-1096587/

**Comment by kuanyingchou** [comment]
On my Nexus 5, the navigation bar can be disabled by adding these lines:

    qemu.hw.mainkeys=1
    <empty line>
    <empty line>

(That's `qemu.hw.mainkeys=1` followed by 2 empty lines)

 to `out/target/product/hammerhead/system/build.prop` in AOSP.

I haven't found a permanent way to disable the top status bar yet.

**Comment by woei66** [comment]
let me survey and I will verify it on ML330
